apiVersion: v1
kind: Service
metadata:
  name: practica-backend
spec:
  selector:
    app: practica-backend
    version: blue  # ← AGREGAR ESTO (cambiará a green)
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  type: ClusterIP
