---
# Servicio ACTIVO (Blue) - Recibe todo el tráfico de producción
apiVersion: v1
kind: Service
metadata:
  name: practica-backend-active
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: practica-backend

---
# Servicio PREVIEW (Green) - Para probar la nueva versión antes de promover
apiVersion: v1
kind: Service
metadata:
  name: practica-backend-preview
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: practica-backend
